import numpy as np

theta = np.random.rand(3)
theta_GD = theta.copy()
theta_HB = theta.copy()
print("theta")
print(theta)
print("theta GD")
print(theta_GD)
print("theta HB")
print(theta_HB)
theta_GD = np.random.rand(4)
theta_HB = np.random.rand(4)
print("------")
print("theta")
print(theta)
print("theta GD")
print(theta_GD)
print("theta HB")
print(theta_HB)
